### ISSUE TITLE
관리가이드 부문 Glue 가이드 문서 작성

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-docs#17]
관리드가이드 부문 중 Glue 가이드 문서 작성이 필요합니다.
ceph 가이드를 참조하여 사용가이드 작성이 필요합니다

**Comment by ycyun** [comment]
참조링크: https://docs.ceph.com/en/pacific/mgr/dashboard/

**Comment by ycyun** [comment]
- [ ] Overview
  - [ ]  Feature Overview
  - [ ]  Overview of the Dashboard Landing Page
    - [ ] Status
    - [ ] Capacity
    - [ ] Performance
  - [ ] supported Browsers
 - [ ] Enabling
- [ ] Configuration
  - [ ] SSL/TLS Support
  - [ ] Host Name and Port
  - [ ] Username and Password
  - [ ] Account Lock-out
  - [ ] Enable a Locked User
  - [ ] Accessing the Dashboard
  - [ ] Enabling the Object Gateway Management Frontend
  - [ ] Enabling iSCSI Management
  - [ ] Enabling the Embedding of Grafana Dashboards
    - [ ] Installation and Configuration using cephadm
    - [ ] Manual Installation and Configuration
    - [ ] Enabling RBD-Image monitoring
    - [ ] Configuring Dashboard
    - [ ] Alternative URL for Browsers
  - [ ] Enabling Single Sign-On (SSO)
  - [ ] Enabling Prometheus Alerting
- [ ] User and Role Management
  - [ ] Password Policy
  - [ ] User Accounts
  - [ ] User Roles and Permissions
  - [ ] Example of User and Custom Role Creation
- [ ] Proxy Configuration
  - [ ] Configuring a URL Prefix
  - [ ] Disable the redirection
  - [ ] Configure the error status code
  - [ ] HAProxy example configuration
- [ ] Auditing API Requests
- [ ] NFS-Ganesha Management
  - [ ] Configuring NFS-Ganesha in the Dashboard
  - [ ] Support for Multiple NFS-Ganesha Clusters
  - [ ] Support for NFS-Ganesha Clusters Deployed by the Orchestrator
- [ ] Plug-ins
  - [ ] Feature Toggles
  - [ ] Debug
- [ ] Troubleshooting the Dashboard
  - [ ] Locating the Dashboard
  - [ ] Accessing the Dashboard
  - [ ] Trouble Logging into the Dashboard
  - [ ] A Dashboard Feature is Not Working
  - [ ] Ceph Dashboard Logs
    - [ ] Dashboard Debug Flag
    - [ ] Setting Logging Level of Dashboard Module

**Comment by kt-cheon** [comment]
- [ ] #20 Overview 
  - [ ]  Feature Overview
  - [ ]  Overview of the Dashboard Landing Page
    - [ ] Status
    - [ ] Capacity
    - [ ] Performance
  - [ ] supported Browsers
- [ ] Enabling
- [ ] #21 Configuration
  - [ ] SSL/TLS Support
  - [ ] Host Name and Port
  - [ ] Username and Password
  - [ ] Account Lock-out
  - [ ] Enable a Locked User
  - [ ] Accessing the Dashboard
  - [ ] Enabling the Object Gateway Management Frontend
  - [ ] Enabling iSCSI Management
  - [ ] Enabling the Embedding of Grafana Dashboards
    - [ ] Installation and Configuration using cephadm
    - [ ] Manual Installation and Configuration
    - [ ] Enabling RBD-Image monitoring
    - [ ] Configuring Dashboard
    - [ ] Alternative URL for Browsers
  - [ ] Enabling Single Sign-On (SSO)
  - [ ] Enabling Prometheus Alerting
- [ ] #22 User and Role Management
  - [ ] Password Policy
  - [ ] User Accounts
  - [ ] User Roles and Permissions
  - [ ] Example of User and Custom Role Creation
- [ ] #23 Proxy Configuration
  - [ ] Configuring a URL Prefix
  - [ ] Disable the redirection
  - [ ] Configure the error status code
  - [ ] HAProxy example configuration
- [ ] #24 Auditing API Requests
- [ ] #25 NFS-Ganesha Management
  - [ ] Configuring NFS-Ganesha in the Dashboard
  - [ ] Support for Multiple NFS-Ganesha Clusters
  - [ ] Support for NFS-Ganesha Clusters Deployed by the Orchestrator
- [ ] #26 Plug-ins
  - [ ] Feature Toggles
  - [ ] Debug
- [ ] #27 Troubleshooting the Dashboard
  - [ ] Locating the Dashboard
  - [ ] Accessing the Dashboard
  - [ ] Trouble Logging into the Dashboard
  - [ ] A Dashboard Feature is Not Working
  - [ ] Ceph Dashboard Logs
    - [ ] Dashboard Debug Flag
    - [ ] Setting Logging Level of Dashboard Module
